### ISSUE TITLE
我想添加个分类，在这里像首页一样发布文章，一篇一篇的那种

### ISSUE THREAD

**Issue by BaYunmo-Lry** [EYHN/hexo-theme-one#39]
分类为 项目，放一些我做的项目的图片和链接，以文章的形式一篇一篇发布，怎么弄。我现在仿照作者的主题配置文件的左边栏，也就是目录那些的格式，加了个项目分类，但是只能像关于我一样跳到page/项目这个路径。是type类型的问题吗，不太懂，type我填的page，填post没反应，填sitelink也没变化，还有href是什么链接也没搞明白，打了个/project/，自己建了个这个文件，想让他跳转到我建的这个里，然后我再里面加文章，但是不行

**Comment by EYHN** [comment]
hexo官方有对分类的介绍
https://hexo.io/zh-cn/docs/front-matter.html

如果要加到左边栏
```
Drawer:
    -
      title: 项目
      type: sitelink
      href: /categories/项目/
      icon: home
```

应该就可以了
