### ISSUE TITLE
請問左邊抽屜的icon生成

### ISSUE THREAD

**Issue by jayzhan211** [EYHN/hexo-theme-one#47]
```
icon:
         type: svg
         date: path
         viewbox
```
我不知道為啥都生不出圖片 
請問這要去哪裡生?
